"""Render a fully-signed approval sheet to PDF.

Generated by the server rather than printed from the browser, because the
filed copy has to be the one the portal vouches for. It carries the same
content the hash was taken over, the signatures as drawn, and the hash itself
— so a copy that leaves the system can still be checked against the record it
came from.
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Image,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

if TYPE_CHECKING:  # pragma: no cover
    from ..models import SprayRecord
    from ..schemas import ApprovalState

NAVY = colors.HexColor("#0f2f22")
LINE = colors.HexColor("#d7dee6")
FAINT = colors.HexColor("#5b6b7a")

_styles = getSampleStyleSheet()
_body = ParagraphStyle("body", parent=_styles["Normal"], fontSize=8.5, leading=11)
_small = ParagraphStyle("small", parent=_body, fontSize=7, textColor=FAINT)
_h1 = ParagraphStyle(
    "h1", parent=_styles["Heading1"], fontSize=15, textColor=NAVY, spaceAfter=2
)
_h2 = ParagraphStyle(
    "h2", parent=_styles["Heading2"], fontSize=9.5, textColor=NAVY, spaceBefore=10,
    spaceAfter=4,
)


def _money(value: object) -> str:
    try:
        return f"Ksh {float(value or 0):,.0f}"
    except (TypeError, ValueError):
        return "—"


def _date(value: object) -> str:
    if not value:
        return "—"
    return str(value)[:10]


def _scouting_window(head) -> str:
    """The scouting window, reading as a single date when it is one day."""
    start = _date(head.scout_report_date)
    end = _date(getattr(head, "scout_report_end_date", None))
    if not start or start == "—":
        return "—"
    return start if end in ("—", start, "") else f"{start} – {end}"


def render_approval_pdf(
    destination: Path,
    records: list["SprayRecord"],
    state: "ApprovalState",
) -> int:
    """Write the sheet and return its size in bytes."""
    head = records[0]
    doc = SimpleDocTemplate(
        str(destination),
        pagesize=A4,
        leftMargin=16 * mm,
        rightMargin=16 * mm,
        topMargin=14 * mm,
        bottomMargin=14 * mm,
        title=f"Spray approval {head.program_id}",
        author="Florisynergy IPM",
    )

    flow: list[object] = [
        Paragraph("Spray Programme Approval", _h1),
        Paragraph(
            f"Programme {head.program_id or '—'} · "
            f"generated {datetime.now(timezone.utc):%d %b %Y %H:%M} UTC",
            _small,
        ),
    ]

    # ── The application ──
    flow += [Paragraph("Application", _h2)]
    details = [
        ("Greenhouse", str(head.greenhouse_id or "—")),
        ("Bed / bay", head.bed_code or "—"),
        ("Partition", head.partition_no or "—"),
        ("Variety", head.variety_code or "—"),
        ("Type", head.type_of_application or "—"),
        ("Coverage", head.coverage or "—"),
        ("Water volume", head.volume_of_water or "—"),
        ("Start", f"{_date(head.start_date)} {head.start_time or ''}".strip()),
        ("Scouting answered", _scouting_window(head)),
        ("Re-entry", f"{head.rei}h" if head.rei else "—"),
    ]
    rows = [
        [
            Paragraph(f"<b>{a[0]}</b><br/>{a[1]}", _body),
            Paragraph(f"<b>{b[0]}</b><br/>{b[1]}", _body),
        ]
        for a, b in zip(details[::2], details[1::2])
    ]
    grid = Table(rows, colWidths=[89 * mm, 89 * mm])
    grid.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ("TOPPADDING", (0, 0), (-1, -1), 2),
            ]
        )
    )
    flow += [grid]

    # ── The tank ──
    flow += [Paragraph("Products", _h2)]
    header = ["Product", "Active ingredient", "WHO", "RAC", "Rate", "Qty", "PHI", "Cost"]
    body = [
        [
            Paragraph(f"<b>{r.product or '—'}</b>", _body),
            Paragraph(
                " + ".join(
                    x for x in (r.active_ingredient1, r.active_ingredient2) if x
                )
                or "—",
                _body,
            ),
            r.who_class or "—",
            r.rac_code or "—",
            r.rate or "—",
            str(r.qty if r.qty is not None else "—"),
            f"{r.phi_days}d" if r.phi_days is not None else "—",
            _money(r.cost_of_chemical),
        ]
        for r in records
    ]
    total = sum(float(r.cost_of_chemical or 0) for r in records)
    body.append(["", "", "", "", "", "", "Total", _money(total)])

    products = Table(
        [header] + body,
        colWidths=[30 * mm, 44 * mm, 12 * mm, 12 * mm, 22 * mm, 15 * mm, 14 * mm, 29 * mm],
        repeatRows=1,
    )
    products.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), NAVY),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTSIZE", (0, 0), (-1, -1), 7.5),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTNAME", (-2, -1), (-1, -1), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.4, LINE),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("ALIGN", (5, 1), (-1, -1), "RIGHT"),
                ("LINEABOVE", (0, -1), (-1, -1), 0.8, NAVY),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ]
        )
    )
    flow += [products]

    safe = [r.safe_harvest_date for r in records if r.safe_harvest_date]
    if safe:
        flow += [
            Spacer(1, 3 * mm),
            Paragraph(
                f"<b>The block cannot be cut until {_date(max(safe))}.</b> "
                "The longest pre-harvest interval in the mix governs.",
                _body,
            ),
        ]
    if head.comments:
        flow += [Paragraph("Comments", _h2), Paragraph(head.comments, _body)]

    # ── The signatures ──
    flow += [Paragraph("Approval", _h2)]
    sig_rows = []
    for st in state.slots:
        sig = st.signature
        mark: object = Paragraph("—", _small)
        if sig and sig.image_url:
            path = _media_path(sig.image_url)
            if path and path.exists():
                # Fixed height, width by aspect — a signature stretched to fit
                # a cell is not the mark the person made.
                mark = Image(str(path), width=38 * mm, height=13 * mm, kind="proportional")
        who = (
            f"<b>{sig.signer_name}</b><br/>"
            f"{sig.signer_role or ''} · {sig.signed_at:%d %b %Y %H:%M} UTC"
            if sig
            else "<i>Unsigned</i>"
        )
        sig_rows.append(
            [
                Paragraph(
                    f"<b>{st.slot.label}</b><br/>"
                    f"<font size=6 color='#5b6b7a'>{st.slot.hint or ''}</font>",
                    _body,
                ),
                mark,
                Paragraph(who, _body),
            ]
        )

    signatures = Table(sig_rows, colWidths=[52 * mm, 60 * mm, 66 * mm])
    signatures.setStyle(
        TableStyle(
            [
                ("GRID", (0, 0), (-1, -1), 0.4, LINE),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    flow += [signatures]

    # ── The proof ──
    flow += [
        Spacer(1, 4 * mm),
        Paragraph(
            "<b>Integrity</b><br/>"
            "This document was generated by Florisynergy IPM when the last "
            "required signature was applied. The fingerprint below is a SHA-256 "
            "hash of the programme content that was signed; the portal recomputes "
            "it on every view, so any later change to the programme is detectable.",
            _small,
        ),
        Spacer(1, 1.5 * mm),
        Paragraph(
            f"<font face='Courier' size='6.5'>{state.signed_hash or state.current_hash}</font>",
            _small,
        ),
    ]

    doc.build(flow)
    return destination.stat().st_size


def _media_path(url: str) -> Path | None:
    """Resolve a stored /media/... url back to a file, refusing anything else.

    A signature url comes from our own writer, but this renders whatever is on
    the record — so it must not be persuadable into reading outside the media
    directory.
    """
    from ..routers.media import MEDIA_DIR

    if not url.startswith("/media/"):
        return None
    name = Path(url[len("/media/"):]).name  # strips any traversal
    if not name:
        return None
    return MEDIA_DIR / name
